### ISSUE TITLE
[RFC] Handle the logs from the agent/VM

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/proxy#10]
I was thinking about the way we will get the logs from the agent, and this made me think that we handle this from the proxy in Clear Containers since this is the component directly connected to the VM. As long as we have a proxy with Kata Containers, we can do the same and listen to a specific socket to get those logs from the agent. But what if we don't have the proxy (VSOCK) ?
I think we should always be able to log everything coming from the VM to our journal on the host.
- I was thinking that a simple way to do that would be to create a `no-proxy` binary which would be started by the runtime the same way we start a regular proxy. But it would do nothing except copying all the logs coming from the VM connected to it.
- Or we could go with a new component that we could call `vm_logger` or `agent_logger`, running it on the system the same way ksm-throttler does. We can even integrate this logging ability to ksm-throttler (but we need a more generic name for ksm-throttler in that case, something like `vmmon`...). From the runtime, we would call into a gRPC API to provide the socket that needs to be listened to capture the logs, and that's it.

With ksm-throttler, the logging, and also the monitoring of shims being killed by a SIGKILL, I think we have a real need for a centralized monitoring process here, and all of this could be integrated into a single server providing all those functionalities. But at the same time, I don't want to end up with a solution where our containers could be compromised if this centralized component is killed and need to be restarted. Basically, I don't want to see some high importance/critical tasks being performed by this component (that's why shim monitoring might not fit with this).

**Comment by sboeuf** [comment]
cc @laijs @bergwolf @gnawux @WeiZhang555 @mcastelino @sameo

**Comment by laijs** [comment]
A similar was just implemented in runv.
https://github.com/hyperhq/runv/pull/641
A runv/watcher program is separated from runv/proxy.

The current only agent for runv is hyperstart, and the log of hyperstart is routed to the vm-console, and the `runv/watcher --watch-vm-console` will save the log into /var/log/hyper.

**Comment by bergwolf** [comment]
@sboeuf I would like to see the agent routing its log via vm console as well. Because it's not only agent's log that we are interested in, we'd want to see kernel boot logs that will be key to identifying boot failures especially when the agent is used as `init` program in the guest. That means we do not rely on vsock to get the logs - we always get it from vm console.

On the host side, I agree with @sboeuf and @laijs that we need a watcher program to collect the logs and save its somewhere properly. It will be a per-guest watcher and we need to monitor it. Runtime should be the one creating the watcher.

**Comment by sboeuf** [comment]
@bergwolf about the vm console, I fully agree. We want all the logs coming from the guest, which means kernel + init + agent logs. And yes, it would be good to rely on the same mechanism for both cases (with or w/o VSOCK), meaning that we only need to create a console.sock when creating the VM. This would be the entry point where the watcher/logger would get all the logs from the VM.

**Comment by sboeuf** [comment]
I think the proposal of a dedicated component is the best choice since it would not be tied to anything in particular. Now, even if having a simple component like the watcher proposed by @laijs is tempting, I think we could try to go one step further and create a real watcher watching anything we would provide to it.
It should be able to listen to any socket we would provide, but also it should allow any component to send some traces to write on its behalf. This would allow us to centralize the logs coming from any component of the system, and this would simplify the tracing/logging.
I would like a decision to be taken on this point so that we can move forward, because this will be an important part of the success of this project. The quality of logging is directly tied to the time we'll spend debugging issues.

**Comment by jodh-intel** [comment]
@sboeuf - +1 for good logging ;)

But I'm not clear what other (implicitly in-VM?) components you're referring to? Is this just a hypothetical generic design or do you have thoughts on extra components? Also, when you say "traces", do you mean stack traces? Or a sequence of log messages? Or a sequence of messages that show the function calls in particular in-VM components maybe (live tracing of component execution)?

**Comment by sboeuf** [comment]
@jodh-intel when I say traces, I mean sequences of log messages (which could include some stack traces if needed, but it does not need to know about that).
When I refer to components, I am thinking about shim, runtime, proxy and agent all going through this watcher to log what they have to log.
You could imagine functions like `Log(context, message)` for proxy, shim and runtime, while we would use something like `Listen(context, socket)` to listen to incoming logs from sockets like `console.sock`.

**Comment by jodh-intel** [comment]
With CC all components (shim, runtime, proxy and indirectly the agent) are logging via the hosts syslog/journald, so I'm still not really clear what we'd gain by having another component to essentially do the same job for the host-side processes?

But stepping back, what would be very neat is the ability to alter the log level of each component separately somehow ("quiet", "firehose" and everything in between ;) Also, some sort of in-built metrics functionality could be very useful.

/cc @grahamwhaley.

**Comment by sboeuf** [comment]
@jodh-intel you've answered your own question here I think. Adding this component would allow to reformat the logs with some headers so that we could do some post processing on the logs based on those specific headers. This would allow us to determine metrics by process/container/pod as you've suggested.

**Comment by jcvenegas** [comment]
The shim already collect the vm logs on when there is not proxy closing issue.
