### ISSUE TITLE
log: Enable syslog logging

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/proxy#22]
It's important for debug that we centralize all logs to the same place. The easiest way for that is to use `syslog`. We will be able to check the logs by running the following command:
```bash
journalctl -f
```

**Comment by bergwolf** [comment]
I'm not sure if syslog is the right place for kata logs. There might be a lot of containers running and all of them are printing to the syslog. Would it make the log hard to read? Maybe a better way is letting each container have its own log file.

**Comment by sameo** [comment]
@bergwolf With logrus you can have structured logging and fairly easily grep for your components specific logs. I find that much easier than having to go through different log files for each components.
