### ISSUE TITLE
Handle SIGTERM gracefully by cleaning up

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/proxy#36]
When the pod is stopped, the proxy will be killed by the runtime, and this should be done by sending a SIGTERM to the proxy. The benefit of SIGTERM is that we can handle it from the proxy itself so that we can properly close the connection with the VM.

**Comment by jshachm** [comment]
and we need a sig_action registered for `SIGTERM`

**Comment by laijs** [comment]
FYI, runv proxy(grpc<->json) quits after DestroySandbox() returned (plus some time).
```go
func (proxy *jsonProxy) DestroySandbox(ctx context.Context, req *kagenta.DestroySandboxRequest) (*google_protobuf.Empty, error) {
        err := proxy.json.DestroySandbox()
        // we can not call proxy.self.GracefulStop() directly, otherwise the err would be "transport is closing"
        time.AfterFunc(10*time.Millisecond, proxy.self.GracefulStop)
        return pbEmpty(err), err
}
```
 SIGTERM might be better.
