### ISSUE TITLE
yamux: keepalive failed: i/o deadline reached

### ISSUE THREAD

**Issue by devimc** [kata-containers/proxy#70]
see https://github.com/kata-containers/agent/issues/231

**Comment by devimc** [comment]
still occurs but now using `docker update`, I found a way to reproduce it  see https://github.com/kata-containers/runtime/issues/352

**Comment by chavafg** [comment]
Found an occurrence of this on a CI job:
```
• Failure [167.604 seconds]
check yamux IO timeout
/home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/pause_test.go:45
  pause, wait and unpause a container
  /home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/pause_test.go:67
    check yamux IO connection
    /home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/pause_test.go:68
      should keep alive [It]
      /home/jenkins/jenkins_slave/workspace/kata-containers-tests-ubuntu-17-10-PR/go/src/github.com/kata-containers/tests/integration/docker/pause_test.go:69

      Expected
          <int>: 0
      to equal
          <int>: -1
```
http://kata-jenkins-ci.westus2.cloudapp.azure.com/job/kata-containers-tests-ubuntu-17-10-PR/400/consoleFull

**Comment by aduenasd** [comment]
Hi,
I'm also hitting this issue when running 
kata-containers/tests/metrics/storage/blogbench.sh
on bare-metal (host Ubuntu and Fedora).

**Comment by devimc** [comment]
@aduenasd tanks for the information, I was able to reproduce.
This patch https://github.com/kata-containers/agent/pull/263 will fix this issue
