### ISSUE TITLE
cmdline: accept a 'sandbox' argument to aid with log annotation

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/proxy#87]
# Description of problem

The proxy does not know (afaict) which sandbox/container it is routing, and thus cannot annotate any logs it generates.

# Expected result

It might aid debugging if we can add the annotation. For instance, on an agent yamux fail, I got:
```
time="2018-07-02T11:49:16.217469645+01:00" level=info msg="2018/07/02 10:49:16 [ERR] yamux: keepalive failed: i/o deadline reached\n" name=kata-proxy pid=25683 source=agent
```

routed out by https://github.com/kata-containers/proxy/blob/master/proxy.go#L187, but it does not indicate which sandbox/container it relates to, and that information is currently not to hand in the proxy.

I think the only way to do this is to pass the sandbox ID in over at https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_proxy.go#L41 on the proxy invocation command line.

**Comment by grahamwhaley** [comment]
@jodh-intel - wdyt?

**Comment by sboeuf** [comment]
@grahamwhaley that sounds like a very good idea. Very cheap to add one argument to the proxy binary.

**Comment by jodh-intel** [comment]
Hi @grahamwhaley - see https://github.com/kata-containers/tests/issues/453#issuecomment-401339364. I assume you're in favour of this too then? :) Would be good to get input from @sboeuf and @bergwolf as it will be "overhead", but arguably worth it ;)

**Comment by sboeuf** [comment]
+1 from me
